- id: https://doi.org/10.1186/s13073-020-00825-3
  #image: 
  date: 20-1-2021
  #extra-links:
    - #type: manubot
      #link: https://greenelab.github.io/knowledge-graph-review/
  #tags:
    - knowledge graphs

- id: https://doi.org/10.3390/microorganisms9081613
  #image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
  #repo: greenelab/meta-review
  #extra-links:
    #- type: manubot
      #link: https://greenelab.github.io/meta-review/
    #- type: source
      #link: https://github.com/greenelab/meta-review
    #- type: website
      #link: http://manubot.org/

- id:  https://doi.org/10.1093/jac/dkaa534
  #image: https://iiif.elifesciences.org/lax:32822%2Felife-32822-fig8-v3.tif/full/863,/0/default.webp
  #extra-links:
    #- type: preprint
     # link: https://doi.org/10.7287/peerj.preprints.3100v1
    #- type: manubot
     # link: https://greenelab.github.io/scihub-manuscript/
    #- type: source
     # link: https://github.com/greenelab/scihub-manuscript
      #text: Manuscript source
    #- type: source
     # link: https://github.com/greenelab/scihub
      #text: Analyses source
