- id: https://doi.org/10.1186/s13073-020-00825-3
   image: 
   date: 
   extra-links:
    -  type: 
       link: 
   tags:
    -

- id: https://doi.org/10.3390/microorganisms9081613
   image:
   repo: 
   extra-links:
     - type: 
       link: 
     - type: 
       link: 
     - type: 
       link: 

- id:  https://doi.org/10.1093/jac/dkaa534
   image: 
   extra-links:
     - type: 
       link: 
     - type: 
       link:
     - type: 
       link:
       text: 
     - type: 
       link: 
       text: 
